#! /usr/bin/env python

import sys, os, time
import subprocess
date = (time.strftime("%m_%d_%Y_%H%M"))
location =  '/tmp/'
report = ('Report' + '.' +  date + '.csv' )
report_out = (location + report)

def email(file):
   import smtplib
   from email.MIMEMultipart import MIMEMultipart
   from email.MIMEBase import MIMEBase
   from email import Encoders
   from email.mime.text import MIMEText


   SUBJECT = ('Openstack cloud Capacity Report' + ' ' + date)

   msg = MIMEMultipart()
   msg['Subject'] = SUBJECT 
   msg['From'] = 'from_email@example.com'
   msg['To'] = ' '.join(['to_email@example.com','to_email2@example.com'])

   part = MIMEBase('application', "octet-stream")
   part.set_payload(open(file, "rb").read())
   Encoders.encode_base64(part)

   part.add_header('Content-Disposition', 'attachment', filename=report)
   msg.attach(MIMEText('Link to URL', 'plain'))

   msg.attach(part)

   server = smtplib.SMTP('localhost')
   server.sendmail('from_email@example.com', ['to_email@example.com','to_email2@example.com'], msg.as_string())
   server.quit()

def ssh_session(host):
   cmd = 'ssh -q' + ' ' +   host + ' ' +  'python /tmp/tenant_util.py'
   with open(report_out, "ab") as f:
      pr = subprocess.Popen(cmd, shell=True, stdout=f)
      pr.wait()
      return pr

def hosts():
   hosts = [ 'hostname' ]
   for host in hosts:
      cmd = 'scp -q /tenant_util.py' + ' ' + host +  ':' + '/tmp'
      pr = subprocess.Popen(cmd, shell=True)
      pr.wait()
      ssh_session(host)

hosts() 
print report_out

email(report_out)
